from flask import Flask, render_template, request, redirect, url_for
import json
import os

app = Flask(__name__)

POSTS_FILE = os.path.join(os.path.dirname(__file__), '..', 'posts.json')


def load_posts():
    if os.path.exists(POSTS_FILE):
        with open(POSTS_FILE, 'r', encoding='utf-8') as f:
            return json.load(f)
    return []


def save_posts(posts):
    with open(POSTS_FILE, 'w', encoding='utf-8') as f:
        json.dump(posts, f, indent=2)


def generate_post(title, prompt):
    # Simple local post generation using a template
    body = f"This is an autogenerated post about {prompt}.\n\n"
    body += (
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. "
        "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    )
    return {
        "title": title,
        "content": body
    }


@app.route('/')
def index():
    posts = load_posts()
    return render_template('index.html', posts=posts)


@app.route('/new', methods=['GET', 'POST'])
def new_post():
    if request.method == 'POST':
        title = request.form.get('title', 'Untitled')
        prompt = request.form.get('prompt', '')
        post = generate_post(title, prompt)
        posts = load_posts()
        posts.append(post)
        save_posts(posts)
        return redirect(url_for('index'))
    return render_template('new_post.html')


if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0')
